name: flu_ecom
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: ">=3.6.0 <4.0.0"

#-----------------------Packages Start------------------------#
dependencies:
  flutter:
    sdk: flutter

  #Utility Package
  http: ^1.1.0
  intl: ^0.20.2
  logger: ^2.5.0
  lottie: ^3.3.1
  url_launcher: ^6.1.12
  connectivity_plus: ^6.1.3
  flutter_native_splash: ^2.4.5
  smooth_page_indicator: ^1.2.1
  

  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  #Stage Management
  get: ^4.7.2
  get_storage: ^2.1.1

  #Product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1

  
  #Firebase
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1

#-----------------------Packages End------------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #-----------------------Local Assets -----------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/icons/payment_methods/

    - assets/images/banners/
    - assets/images/content/
    - assets/images/reviews/
    - assets/images/products/
    - assets/images/animations/
    - assets/images/on_boarding_images/

  #-----------------------Local Fonts -----------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/icons/Poppins-Light.ttf
          weight: 300
        - asset: assets/icons/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/icons/Poppins-Regular.ttf
          weight: 400
        - asset: assets/icons/Poppins-Italic.ttf
          style: italic
        - asset: assets/icons/Poppins-Medium.ttf
          weight: 500
        - asset: assets/icons/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/icons/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/icons/Poppins-Bold.ttf
          weight: 800
        - asset: assets/icons/Poppins-BoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/icons/Poppins-ExtraBold.ttf
          weight: 900
        - asset: assets/icons/Poppins-ExtraBoldItalic.ttf
          weight: 900
          style: italic
